CREATE TABLE orders (
    `Order ID` INT,
    `Order Item ID` INT,
    `Order YearMonth` VARCHAR(20),
    `Order Year` INT,
    `Order Month` INT,
    `Order Day` INT,
    `Order Time` TIME,
    `Order Quantity` INT,
    `Product Department` VARCHAR(255),
    `Product Category` VARCHAR(255),
    `Product Name` VARCHAR(255),
    `Customer ID` INT,
    `Customer Market` VARCHAR(255),
    `Customer Region` VARCHAR(255),
    `Customer Country` VARCHAR(255),
    `Warehouse Country` VARCHAR(255),
    `Shipment Year` INT,
    `Shipment Month` INT,
    `Shipment Day` INT,
    `Shipment Mode` VARCHAR(255),
    `Shipment Days - Scheduled` INT,
    `Gross Sales` DECIMAL(10, 2),
    `Discount %` VARCHAR(255),
    `Profit` DECIMAL(10, 2),
    `Product ID` INT,
    `Index` INT PRIMARY KEY
);

